apiVersion: v1
kind: Service
metadata:
  name: cloud-native-service
spec:
  type: LoadBalancer
  selector:
    app: cloud-native-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
